image: gcc

before_script:
 - apt-get update --yes
 - apt-get install --yes cmake libboost-all-dev apt-get install root-system

build:
  script:
  - cmake .
  - make
  artifacts:
    paths:
    - analysis