image: gcc

before_script:
 - mkdir /var/lib/apt/lists/partial
 - apt-get update --yes
 - apt-get install --yes cmake libboost-all-dev git cmake dpkg-dev python-dev make g++ gcc binutils libx11-dev libxpm-dev libxft-dev libxext-dev 
 - wget https://root.cern.ch/download/root_v6.14.06.Linux-ubuntu18-x86_64-gcc7.3.tar.gz
 - tar xvfz root_v6.14.06.Linux-ubuntu18-x86_64-gcc7.3.tar.gz
 - sed -i '1s/^/set -x\n/' root/bin/thisroot.sh
 - . root/bin/thisroot.sh
 - cd ..
 
build:
  script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make