# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/local/software/cmake/3.8.2/bin/cmake

# The command to remove a file.
RM = /home/local/software/cmake/3.8.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dam1g09/apsis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dam1g09/apsis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/local/software/cmake/3.8.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/local/software/cmake/3.8.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dam1g09/apsis/CMakeFiles /home/dam1g09/apsis/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dam1g09/apsis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named analysis

# Build rule for target.
analysis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 analysis
.PHONY : analysis

# fast build rule for target.
analysis/fast:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/build
.PHONY : analysis/fast

src/analysis.o: src/analysis.cpp.o

.PHONY : src/analysis.o

# target to build an object file
src/analysis.cpp.o:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/analysis.cpp.o
.PHONY : src/analysis.cpp.o

src/analysis.i: src/analysis.cpp.i

.PHONY : src/analysis.i

# target to preprocess a source file
src/analysis.cpp.i:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/analysis.cpp.i
.PHONY : src/analysis.cpp.i

src/analysis.s: src/analysis.cpp.s

.PHONY : src/analysis.s

# target to generate assembly for a file
src/analysis.cpp.s:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/analysis.cpp.s
.PHONY : src/analysis.cpp.s

src/atlas-style.o: src/atlas-style.cpp.o

.PHONY : src/atlas-style.o

# target to build an object file
src/atlas-style.cpp.o:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/atlas-style.cpp.o
.PHONY : src/atlas-style.cpp.o

src/atlas-style.i: src/atlas-style.cpp.i

.PHONY : src/atlas-style.i

# target to preprocess a source file
src/atlas-style.cpp.i:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/atlas-style.cpp.i
.PHONY : src/atlas-style.cpp.i

src/atlas-style.s: src/atlas-style.cpp.s

.PHONY : src/atlas-style.s

# target to generate assembly for a file
src/atlas-style.cpp.s:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/atlas-style.cpp.s
.PHONY : src/atlas-style.cpp.s

src/bool-to-string.o: src/bool-to-string.cpp.o

.PHONY : src/bool-to-string.o

# target to build an object file
src/bool-to-string.cpp.o:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/bool-to-string.cpp.o
.PHONY : src/bool-to-string.cpp.o

src/bool-to-string.i: src/bool-to-string.cpp.i

.PHONY : src/bool-to-string.i

# target to preprocess a source file
src/bool-to-string.cpp.i:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/bool-to-string.cpp.i
.PHONY : src/bool-to-string.cpp.i

src/bool-to-string.s: src/bool-to-string.cpp.s

.PHONY : src/bool-to-string.s

# target to generate assembly for a file
src/bool-to-string.cpp.s:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/bool-to-string.cpp.s
.PHONY : src/bool-to-string.cpp.s

src/get-parameter.o: src/get-parameter.cpp.o

.PHONY : src/get-parameter.o

# target to build an object file
src/get-parameter.cpp.o:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/get-parameter.cpp.o
.PHONY : src/get-parameter.cpp.o

src/get-parameter.i: src/get-parameter.cpp.i

.PHONY : src/get-parameter.i

# target to preprocess a source file
src/get-parameter.cpp.i:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/get-parameter.cpp.i
.PHONY : src/get-parameter.cpp.i

src/get-parameter.s: src/get-parameter.cpp.s

.PHONY : src/get-parameter.s

# target to generate assembly for a file
src/get-parameter.cpp.s:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/get-parameter.cpp.s
.PHONY : src/get-parameter.cpp.s

src/highest-pt.o: src/highest-pt.cpp.o

.PHONY : src/highest-pt.o

# target to build an object file
src/highest-pt.cpp.o:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/highest-pt.cpp.o
.PHONY : src/highest-pt.cpp.o

src/highest-pt.i: src/highest-pt.cpp.i

.PHONY : src/highest-pt.i

# target to preprocess a source file
src/highest-pt.cpp.i:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/highest-pt.cpp.i
.PHONY : src/highest-pt.cpp.i

src/highest-pt.s: src/highest-pt.cpp.s

.PHONY : src/highest-pt.s

# target to generate assembly for a file
src/highest-pt.cpp.s:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/highest-pt.cpp.s
.PHONY : src/highest-pt.cpp.s

src/kinematic-reconstructer.o: src/kinematic-reconstructer.cpp.o

.PHONY : src/kinematic-reconstructer.o

# target to build an object file
src/kinematic-reconstructer.cpp.o:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/kinematic-reconstructer.cpp.o
.PHONY : src/kinematic-reconstructer.cpp.o

src/kinematic-reconstructer.i: src/kinematic-reconstructer.cpp.i

.PHONY : src/kinematic-reconstructer.i

# target to preprocess a source file
src/kinematic-reconstructer.cpp.i:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/kinematic-reconstructer.cpp.i
.PHONY : src/kinematic-reconstructer.cpp.i

src/kinematic-reconstructer.s: src/kinematic-reconstructer.cpp.s

.PHONY : src/kinematic-reconstructer.s

# target to generate assembly for a file
src/kinematic-reconstructer.cpp.s:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/kinematic-reconstructer.cpp.s
.PHONY : src/kinematic-reconstructer.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/match-bjets-to-leps.o: src/match-bjets-to-leps.cpp.o

.PHONY : src/match-bjets-to-leps.o

# target to build an object file
src/match-bjets-to-leps.cpp.o:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/match-bjets-to-leps.cpp.o
.PHONY : src/match-bjets-to-leps.cpp.o

src/match-bjets-to-leps.i: src/match-bjets-to-leps.cpp.i

.PHONY : src/match-bjets-to-leps.i

# target to preprocess a source file
src/match-bjets-to-leps.cpp.i:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/match-bjets-to-leps.cpp.i
.PHONY : src/match-bjets-to-leps.cpp.i

src/match-bjets-to-leps.s: src/match-bjets-to-leps.cpp.s

.PHONY : src/match-bjets-to-leps.s

# target to generate assembly for a file
src/match-bjets-to-leps.cpp.s:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/match-bjets-to-leps.cpp.s
.PHONY : src/match-bjets-to-leps.cpp.s

src/neutrino-weighter.o: src/neutrino-weighter.cpp.o

.PHONY : src/neutrino-weighter.o

# target to build an object file
src/neutrino-weighter.cpp.o:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/neutrino-weighter.cpp.o
.PHONY : src/neutrino-weighter.cpp.o

src/neutrino-weighter.i: src/neutrino-weighter.cpp.i

.PHONY : src/neutrino-weighter.i

# target to preprocess a source file
src/neutrino-weighter.cpp.i:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/neutrino-weighter.cpp.i
.PHONY : src/neutrino-weighter.cpp.i

src/neutrino-weighter.s: src/neutrino-weighter.cpp.s

.PHONY : src/neutrino-weighter.s

# target to generate assembly for a file
src/neutrino-weighter.cpp.s:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/neutrino-weighter.cpp.s
.PHONY : src/neutrino-weighter.cpp.s

src/progress-bar.o: src/progress-bar.cpp.o

.PHONY : src/progress-bar.o

# target to build an object file
src/progress-bar.cpp.o:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/progress-bar.cpp.o
.PHONY : src/progress-bar.cpp.o

src/progress-bar.i: src/progress-bar.cpp.i

.PHONY : src/progress-bar.i

# target to preprocess a source file
src/progress-bar.cpp.i:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/progress-bar.cpp.i
.PHONY : src/progress-bar.cpp.i

src/progress-bar.s: src/progress-bar.cpp.s

.PHONY : src/progress-bar.s

# target to generate assembly for a file
src/progress-bar.cpp.s:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/progress-bar.cpp.s
.PHONY : src/progress-bar.cpp.s

src/semilepton-reconstructer.o: src/semilepton-reconstructer.cpp.o

.PHONY : src/semilepton-reconstructer.o

# target to build an object file
src/semilepton-reconstructer.cpp.o:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/semilepton-reconstructer.cpp.o
.PHONY : src/semilepton-reconstructer.cpp.o

src/semilepton-reconstructer.i: src/semilepton-reconstructer.cpp.i

.PHONY : src/semilepton-reconstructer.i

# target to preprocess a source file
src/semilepton-reconstructer.cpp.i:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/semilepton-reconstructer.cpp.i
.PHONY : src/semilepton-reconstructer.cpp.i

src/semilepton-reconstructer.s: src/semilepton-reconstructer.cpp.s

.PHONY : src/semilepton-reconstructer.s

# target to generate assembly for a file
src/semilepton-reconstructer.cpp.s:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/semilepton-reconstructer.cpp.s
.PHONY : src/semilepton-reconstructer.cpp.s

src/solve-poly.o: src/solve-poly.cpp.o

.PHONY : src/solve-poly.o

# target to build an object file
src/solve-poly.cpp.o:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/solve-poly.cpp.o
.PHONY : src/solve-poly.cpp.o

src/solve-poly.i: src/solve-poly.cpp.i

.PHONY : src/solve-poly.i

# target to preprocess a source file
src/solve-poly.cpp.i:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/solve-poly.cpp.i
.PHONY : src/solve-poly.cpp.i

src/solve-poly.s: src/solve-poly.cpp.s

.PHONY : src/solve-poly.s

# target to generate assembly for a file
src/solve-poly.cpp.s:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/solve-poly.cpp.s
.PHONY : src/solve-poly.cpp.s

src/solve-quartic.o: src/solve-quartic.cpp.o

.PHONY : src/solve-quartic.o

# target to build an object file
src/solve-quartic.cpp.o:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/solve-quartic.cpp.o
.PHONY : src/solve-quartic.cpp.o

src/solve-quartic.i: src/solve-quartic.cpp.i

.PHONY : src/solve-quartic.i

# target to preprocess a source file
src/solve-quartic.cpp.i:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/solve-quartic.cpp.i
.PHONY : src/solve-quartic.cpp.i

src/solve-quartic.s: src/solve-quartic.cpp.s

.PHONY : src/solve-quartic.s

# target to generate assembly for a file
src/solve-quartic.cpp.s:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/solve-quartic.cpp.s
.PHONY : src/solve-quartic.cpp.s

src/trim.o: src/trim.cpp.o

.PHONY : src/trim.o

# target to build an object file
src/trim.cpp.o:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/trim.cpp.o
.PHONY : src/trim.cpp.o

src/trim.i: src/trim.cpp.i

.PHONY : src/trim.i

# target to preprocess a source file
src/trim.cpp.i:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/trim.cpp.i
.PHONY : src/trim.cpp.i

src/trim.s: src/trim.cpp.s

.PHONY : src/trim.s

# target to generate assembly for a file
src/trim.cpp.s:
	$(MAKE) -f CMakeFiles/analysis.dir/build.make CMakeFiles/analysis.dir/src/trim.cpp.s
.PHONY : src/trim.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... analysis"
	@echo "... src/analysis.o"
	@echo "... src/analysis.i"
	@echo "... src/analysis.s"
	@echo "... src/atlas-style.o"
	@echo "... src/atlas-style.i"
	@echo "... src/atlas-style.s"
	@echo "... src/bool-to-string.o"
	@echo "... src/bool-to-string.i"
	@echo "... src/bool-to-string.s"
	@echo "... src/get-parameter.o"
	@echo "... src/get-parameter.i"
	@echo "... src/get-parameter.s"
	@echo "... src/highest-pt.o"
	@echo "... src/highest-pt.i"
	@echo "... src/highest-pt.s"
	@echo "... src/kinematic-reconstructer.o"
	@echo "... src/kinematic-reconstructer.i"
	@echo "... src/kinematic-reconstructer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/match-bjets-to-leps.o"
	@echo "... src/match-bjets-to-leps.i"
	@echo "... src/match-bjets-to-leps.s"
	@echo "... src/neutrino-weighter.o"
	@echo "... src/neutrino-weighter.i"
	@echo "... src/neutrino-weighter.s"
	@echo "... src/progress-bar.o"
	@echo "... src/progress-bar.i"
	@echo "... src/progress-bar.s"
	@echo "... src/semilepton-reconstructer.o"
	@echo "... src/semilepton-reconstructer.i"
	@echo "... src/semilepton-reconstructer.s"
	@echo "... src/solve-poly.o"
	@echo "... src/solve-poly.i"
	@echo "... src/solve-poly.s"
	@echo "... src/solve-quartic.o"
	@echo "... src/solve-quartic.i"
	@echo "... src/solve-quartic.s"
	@echo "... src/trim.o"
	@echo "... src/trim.i"
	@echo "... src/trim.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

